# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: MX_#1
    check: "tcp-ping"
    url: 202.175.34.59
    port: 25
  - name: MX_#2
    check: "tcp-ping"
    url: 43.247.27.59
    port: 25
  - name: SMTP_#1
    check: "tcp-ping"
    url: 43.247.27.58
    port: 465
  - name: SMTP_#2
    check: "tcp-ping"
    url: 202.175.34.58
    port: 465
  - name: IMAP_#1
    check: "tcp-ping"
    url: 43.247.27.58
    port: 993
  - name: IMAP_#2
    check: "tcp-ping"
    url: 202.175.34.58
    port: 993
  - name: POP_#1
    check: "tcp-ping"
    url: 43.247.27.58
    port: 995
  - name: POP_#2
    check: "tcp-ping"
    url: 202.175.34.58
    port: 995

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /sa-m
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
